!vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvC
!                                                                      C
!  Module name: cp_fun1.inc                                            C
!  Purpose: This is an include file containing all CP function         C
!                                                     variables        C
!                                                                      C
!  Author: S. Venkatesan                              Date: dd-mmm-yy  C
!  Reviewer:                                          Date: dd-mmm-yy  C
!                                                                      C
!  Revision Number:                                                    C
!  Purpose:                                                            C
!  Author:                                            Date: dd-mmm-yy  C
!  Reviewer:                                          Date: dd-mmm-yy  C
!                                                                      C
!  Literature/Document References:                                     C
!                                                                      C
!  Variables referenced: None.                                         C
!  Variables modified: None.                                           C
!                                                                      C
!  Local variables: ZZZ                                                C
!                                                                      C
!^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^C
!
!                         constant-pressure heat capacities (Cp's)!
      DOUBLE PRECISION CPO2, CPCO, CPCO2, CPCH4, CPH2, CPH2O, CPH2S, &
                      CPN2, CPNH3, CPTAR, CPC2H4, CPC2H6, CPC3H8, &
                      CPC6H6, CPFC, CPVM, CPM, CPA
!
