MODULE dsdgmr_a

      INTEGER, PARAMETER :: NSAVE = 10 
      INTEGER, PARAMETER :: LENIW = 31 

      INTEGER LENW, NELTMAX
!
! arrays in leq_dsdgmr
      INTEGER, DIMENSION(:), ALLOCATABLE :: IA, JA 
      INTEGER, DIMENSION(:), ALLOCATABLE :: IWORK 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: A 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: RWORK 

END MODULE dsdgmr_a
