MODULE dslugm_a
      INTEGER, PARAMETER :: NSAVE = 10 
      INTEGER  :: LENW 
      INTEGER  :: LENIW  
      INTEGER  :: NELTMAX 
      
      INTEGER, DIMENSION(:), ALLOCATABLE :: IA, JA 
      INTEGER, DIMENSION(:), ALLOCATABLE :: IWORK 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: A 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: RWORK 

END MODULE dslugm_a
