MODULE dslucs_a
      INTEGER  :: LENW 
      INTEGER  :: LENIW
      INTEGER  :: NELTMAX
      
      INTEGER, DIMENSION(:), ALLOCATABLE :: IA, JA 
      INTEGER, DIMENSION(:), ALLOCATABLE :: IWORK 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: A 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: RWORK 

END MODULE dslucs_a
