!
!                      Dummy arguments
      DOUBLE PRECISION XXXp, XXXm
!
!                      Dummy indices
      INTEGER          xL
!
!                      average at i+1/2 location
      DOUBLE PRECISION AVG_X
!
!                      average (of U) at i+1 location
      DOUBLE PRECISION AVG_X_E
!
!                      average at j+1/2 location
      DOUBLE PRECISION AVG_Y
!
!                      average (of V) at j+1 location
      DOUBLE PRECISION AVG_Y_N
!
!                      average at k+1/2 location
      DOUBLE PRECISION AVG_Z
!
!                      average (of W) at k+1 location
      DOUBLE PRECISION AVG_Z_T
!
!                      Harmonic average at i+1/2 location
      DOUBLE PRECISION AVG_X_h
!
!                      Harmonic averageat j+1/2 location
      DOUBLE PRECISION AVG_Y_h
!
!                      Harmonic average at k+1/2 location
      DOUBLE PRECISION AVG_Z_h
!
!    Averaging for possibly negative scalars (sof, Aug 22 2006)
!                      Harmonic average at i+1/2 location
      DOUBLE PRECISION AVG_X_S
!
!                      Harmonic averageat j+1/2 location
      DOUBLE PRECISION AVG_Y_S
!
!                      Harmonic average at k+1/2 location
      DOUBLE PRECISION AVG_Z_S
