MODULE igcg_a




      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BD00N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BL09N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BL03N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BL01N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BU09N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BU03N 
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: BU01N 


!HPF$ align with BD00N :: BL09N, BL03N, BL01N, BU09N, BU03N, BU01N

END MODULE igcg_a
