      DOUBLE PRECISION INV_H, NEG_H, dPodEP_s
!
!     parameters for P_s = a_ps*(EP_star - EP_g)**b_ps
      DOUBLE PRECISION, PARAMETER          :: a_ps = 1D25
      INTEGER, PARAMETER                   :: b_ps = 10


!     coefficient in Jackson's model (dyne/cm^2)
!      DOUBLE PRECISION, PARAMETER          :: A_ps_jackson = 0.5D0*100D0*2D0*981D0*0.4D0
!     voidage of random close-packed bed
!      DOUBLE PRECISION, PARAMETER          :: EP_g_cp = 0.35D0

