#!/bin/bash -lex

module load autoconf/2.69
module load gnu/4.6.4

module list

MFIX=${MFIX_HOME-"../../../"}

GCC_DBGFLAGS="-fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow"
${MFIX}/configure_mfix FC=gfortran FCFLAGS="-O0 $GCC_DBGFLAGS" || exit $?
make clean
make || exit $?

rm -f POST_*.dat &> /dev/null

RUN_NAME="DEM05"

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_COLL_MODEL=\"LSD\" \
  KN=1.72d7 KT_FAC="@(1.48/1.72)" KN_W=1.72d7 KT_W_FAC="@(1.48/1.72)" \
  "DES_EN_INPUT(1:3)=3*1.0 DES_EN_WALL_INPUT(1:2)=2*1.0"

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_COLL_MODEL=\"HERTZIAN\" \
  "E_YOUNG(1)=380.0d9 E_YOUNG(2)=70.0d9 Ew_YOUNG=70.0d9" \
  "V_POISSON(1)=0.23  V_POISSON(2)=0.25 Vw_POISSON=0.25" \
  "DES_EN_INPUT(1:3)=3*1.0 DES_EN_WALL_INPUT(1:2)=2*1.0" \
  "DES_ET_INPUT(1:3)=3*1.0 DES_ET_WALL_INPUT(1:2)=2*1.0"

##diff -q POST_posvel.dat AUTOTEST/POST_posvel.dat
