stages:
  - build
  - build:py
  - deploy

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# Build stage builds

build:linux:
  stage: build
  script:
    - ./configure
    - make
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - linux

build:mac:
  stage: build
  script:
    - ./configure
    - make
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - mac

# build:windows:
#   stage: build
#   script:
#     - ./configure
#     - make
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - build
#     - .build
#   tags:
#     - windows

build:linux:py:
  stage: build:py
  script:
    - git clean -fdx
    - python2.7 setup.py bdist_wheel
    - python3.5 setup.py bdist_wheel
  dependencies:
    - build:linux
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - linux

build:mac:py:
  stage: build:py
  script:
    - git clean -fdx
    - FC=gfortran-6 CC=gcc-6 python2.7 setup.py bdist_wheel
    - FC=gfortran-6 CC=gcc-6 python3.5 setup.py bdist_wheel
  dependencies:
    - build:mac
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mac

# build:windows:py:
#   stage: build:py
#   script:
#     - git clean -fdx
#     - python2.7 setup.py bdist_wheel
#   dependencies:
#     - build:windows
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfixgui*.whl
#   only:
#     - branches
#   tags:
#     - windows

install:linux:py:
  stage: deploy
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfixgui || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*py2*.whl --prefix=${PYPATH}
  dependencies:
    - build:linux:py
  only:
    - branches
  tags:
    - linux
