#image: python:2.7

cache:
  key: "$CI_BUILD_NAME"
  untracked: true
  paths:
    - build/

before_script:
  - Xvfb :1 &
  - export DISPLAY=:1

stages:
  - test

with_exe:
  stage: test
  script:
    - pushd tutorials/FluidBed_DES
    - ../../configure_mfix --python && make -j mfix
    - popd
    - MFIX_NO_VTK=yes python -m unittest discover -s gui -v
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2

without_exe:
  stage: test
  script:
    - find -name mfix | xargs rm
    - find -name pymfix | xargs rm
    - MFIX_NO_VTK=yes python -m unittest discover -s gui -v
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
