stages:
  - build:src
  - build:libmfix
  - build:py2
  - build:py3
  - deploy

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# build:src builds a source distribution tarball

build:src:
  stage: build:src
  script:
    - python setup.py sdist
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/*.tar.gz
  tags:
    - linux

# build stage builds only Fortran code (libmfix.a)

build:linux:
  stage: build:libmfix
  script:
    - python setup.py build_mfix
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - linux

build:mac:
  stage: build:libmfix
  script:
    - python3.5 setup.py build_mfix
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - mac

build:windows:
  stage: build:libmfix
  script:
    - python setup.py build_mfix
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - windows


# build:py stage builds Python mfixsolver extension and Python wheel packages

build_linux_py2:
  stage: build:py2
  script:
    - python2.7 setup.py bdist_wheel
  dependencies:
    - build:linux
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - linux

build_linux_py3:
  stage: build:py3
  script:
    - python3.5 setup.py bdist_wheel
  dependencies:
    - build:linux
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - linux

build_mac_py2:
  stage: build:py2
  script:
    - FC=gfortran-6 CC=gcc-6 $HOME/anaconda2/bin/python2.7 setup.py bdist_wheel
  dependencies:
    - build:mac
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mac

build_mac_py3:
  stage: build:py3
  script:
    - FC=gfortran-6 CC=gcc-6 python3.5 setup.py bdist_wheel
  dependencies:
    - build:mac
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mac

build_windows_py2:
  stage: build:py2
  script:
    - python2.7 setup.py bdist_wheel
  dependencies:
    - build:windows
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - windows


# install stage installs wheel package on Joule

install:linux:py:
  stage: deploy
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfixgui || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*27*.whl --prefix=${PYPATH}
  dependencies:
    - build:linux:py
  only:
    - branches
  tags:
    - linux
