#image: python:2.7

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - build/

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - pip install packaging
    - git clean -fdx
    - make -C gui ../mfix
  artifacts:
    paths:
    - mfix
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2

test_job:
  stage: test
  script:
    - make -C gui test
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
