#image: python:2.7

cache:
  key: "$CI_BUILD_NAME"
  untracked: true
  paths:
    - build/

stages:
  - test

with_exe:
  stage: test
  script:
    - pushd gui
    - ../configure_mfix --python && make -j mfix
    - popd
    - make test
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2

without_exe:
  stage: test
  script:
    - pushd gui
    - ../configure_mfix --python && make -j
    - popd
    - find . -type f -name mfix -exec rm -f {} \;
    - find . -type f -name pymfix -exec rm -f {} \;
    - make test
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
