stages:
  # - test
  - build
  - deploy

variables:
  AC_BIN: "/nfs/apps/autoconf/2.69/gnu/4.6.4/bin"
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  GCC_BIN: "/nfs/apps/Compilers/GNU/6.1.0/bin"
  JENKINS_HOME: "/nfs/home/0/users/jenkins/jenkins_home"
  MINICONDA_BIN: "/nfs/home/0/users/jenkins/miniconda3/bin"
  MINICONDA_BLD: "/nfs/home/0/users/jenkins/miniconda3/conda-bld"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# test:
#   script:
#     - python setup.py test_load_all
#   stage: test
#   only:
#     - develop
#     - tags
#   tags:
#     - windows

# build:src builds a source distribution tarball

# build:src:
#   script:
#     - env PATH="$AC_BIN:$GCC_BIN:$MINICONDA_BIN:$PATH" python2.7 setup.py sdist
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/*.tar.gz
#   tags:
#     - linux

linux_py2_conda:
  variables:
    CONDA_BLD_PATH: "/home/dev/conda-bld"
  script:
    - rm -rf dist
    - rm -f $CONDA_BLD_PATH/linux-64/mfix*
    - env CONDA_BLD_PATH="$CONDA_BLD_PATH" conda build --python 2.7 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp $CONDA_BLD_PATH/linux-64/mfix* dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/linux-64/mfix*
  tags:
    - docker

linux_py34_conda:
  variables:
    CONDA_BLD_PATH: "/home/dev/conda-bld"
  script:
    - rm -rf dist
    - rm -f $CONDA_BLD_PATH/linux-64/mfix*
    - env CONDA_BLD_PATH="$CONDA_BLD_PATH" conda build --python 3.4 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp $CONDA_BLD_PATH/linux-64/mfix* dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/linux-64/mfix*
  tags:
    - docker

linux_py35_conda:
  variables:
    CONDA_BLD_PATH: "/home/dev/conda-bld"
  script:
    - rm -rf dist
    - rm -f $CONDA_BLD_PATH/linux-64/mfix*
    - env CONDA_BLD_PATH="$CONDA_BLD_PATH" conda build --python 3.5 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp $CONDA_BLD_PATH/linux-64/mfix* dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/linux-64/mfix*
  tags:
    - docker

linux_py36_conda:
  variables:
    CONDA_BLD_PATH: "/home/dev/conda-bld"
  script:
    - rm -rf dist
    - rm -f $CONDA_BLD_PATH/linux-64/mfix*
    - env CONDA_BLD_PATH="$CONDA_BLD_PATH" conda build --python 3.6 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp $CONDA_BLD_PATH/linux-64/mfix* dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/linux-64/mfix*
  tags:
    - docker

linux_py2_whl:
  variables:
    JENKINS: "/nfs/home/0/users/jenkins"
  script:
    - rm -rf dist
    - rm -f /home/dev/conda-bld/linux-64/*.whl
    - env OUTPUT_TYPE_WHEEL=1 CONDA_BLD_PATH=/home/dev/conda-bld conda build --python 2.7 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp /home/dev/conda-bld/linux-64/*.whl dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/linux-64/*.whl
  tags:
    - docker

# mac_py36_conda:
#   script:
#     - rm -rf dist
#     - mkdir -p dist/mac-64
#     - conda build --python 3.6 --output-folder dist build-aux/meta.yaml
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#       - dist/mac-64/mfix*
#   tags:
#     - mac

# windows_py2_conda:
#   script:
#     - rm -rf dist
#     - mkdir dist
#     - env conda build --python 2.7 --output-folder dist build-aux/meta.yaml
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#       - dist/win-64/mfix*
#   tags:
#     - windows

# windows_py34_conda:
#   script:
#     - rm -rf dist
#     - mkdir dist
#     - env conda build --python 3.4 --output-folder dist build-aux/meta.yaml
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#       - dist/win-64/mfix*
#   tags:
#     - windows

windows_py35_conda:
  variables:
    CONDA_BLD_PATH: "C:/conda_bld"
  script:
    - rm -rf dist
    - rm -f $CONDA_BLD_PATH/linux-64/mfix*
    - env CONDA_BLD_PATH="$CONDA_BLD_PATH" conda build --python 3.5 build-aux/meta.yaml
    - mkdir -p dist/linux-64
    - cp $CONDA_BLD_PATH/linux-64/mfix* dist/linux-64
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/win-64/mfix*
  tags:
    - windows

# windows_py3_whl:
#   script:
#     - rm -rf dist
#     - bash -c "mkdir -p dist/win-64"
#     - python setup.py bdist_wheel
#     - mv dist/*.whl dist/win-64
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#       - dist/win-64/mfix*
#   tags:
#     - windows

# install:pip_update:
#   script:
#     - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfix || true
#     - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/linux-64/*27*.whl --prefix=${PYPATH}
#   stage: deploy
#   only:
#     - develop
#     - tags
#   dependencies:
#     - linux_py2_whl
#   tags:
#     - linux

# install:conda_update:
#   variables:
#     CONDA_BIN: /opt/miniconda3/bin
#     CONDA_REPO: /var/www/html/dist
#   script:
#     - rsync -rv dist/ ${CONDA_REPO}/
#     - $CONDA_BIN/conda index ${CONDA_REPO}/linux-64
#     - $CONDA_BIN/conda index ${CONDA_REPO}/mac-64
#     - $CONDA_BIN/conda index ${CONDA_REPO}/win-64
#   stage: deploy
#   only:
#     - develop
#     - tags
#   dependencies:
#     - linux_py2_conda
#     - linux_py2_whl
#     - linux_py34_conda
#     - linux_py35_conda
#     - linux_py36_conda
#     - mac_py36_conda
#     - windows_py2_conda
#     - windows_py34_conda
#     - windows_py35_conda
#     - windows_py3_whl
#   tags:
#     - conda

# install:pylint_update:
#   script:
#     - ( export MFIXHOME=$PWD; cd ${JENKINS_HOME}/userContent; env PYLINTRC="$MFIXHOME/.pylintrc" PYTHONPATH="$MFIXHOME" PATH="$MINICONDA_BIN:$PATH" pylint --files-output=y -f html mfixgui )  || exit 0 # $?
#   stage: deploy
#   only:
#     - develop
#     - tags
#   tags:
#     - linux
