stages:
  - test
  - build:src
  - build:libmfix
  - build:py2
  - build:py3
  - deploy

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  MINICONDA_BIN: "/nfs/home/0/users/jenkins/miniconda2/bin"
  MINICONDA3_BIN: "/nfs/home/0/users/jenkins/miniconda3/bin"
  AC_BIN: "/nfs/apps/autoconf/2.69/gnu/4.6.4/bin"
  GCC_BIN: "/nfs/apps/Compilers/GNU/6.1.0/bin"

  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# test:
#   script:
#     - python setup.py test_load_all
#   stage: test
#   only:
#     - develop
#     - tags
#   tags:
#     - windows

# build:src builds a source distribution tarball

build:src:
  script:
    - env PATH="$MINICONDA_BIN:$PATH" python2.7 setup.py sdist
  stage: build:src
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/*.tar.gz
  tags:
    - linux

# build stage builds only Fortran code (libmfix.a)

build:linux:
  script:
    - env PATH="$AC_BIN:$GCC_BIN:$MINICONDA_BIN:$PATH" python2.7 setup.py build_mfix
  stage: build:libmfix
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - linux

build:mac:
  script:
    - python3.6 setup.py build_mfix
  stage: build:libmfix
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - mac

build:windows:
  script:
    - python setup.py build_mfix
  stage: build:libmfix
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - build
    - .build
  tags:
    - windows


# build:py2 stage builds python2 wheel packages

build_linux_py2:
  script:
    - env PATH="$AC_BIN:$GCC_BIN:$MINICONDA_BIN:$PATH" python2.7 setup.py build_mfix
  stage: build:py2
  only:
    - develop
    - tags
  dependencies:
    - build:linux
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - linux

# build_mac_py2:
#   script:
#     - FC=gfortran-6 CC=gcc-6 $HOME/anaconda2/bin/python2.7 setup.py bdist_wheel
#   stage: build:py2
#   only:
#     - develop
#     - tags
#   dependencies:
#     - build:mac
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:
#     - mac

# build_windows_py2:
#   script:
#     - python2.7 setup.py bdist_wheel
#   stage: build:py2
#   only:
#     - develop
#     - tags
#   dependencies:
#     - build:windows
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:
#     - windows


# build:py3 stage builds python3 wheel packages

build_linux_py3:
  script:
    - env PATH="$AC_BIN:$GCC_BIN:$MINICONDA3_BIN:$PATH" python3.6 setup.py bdist_wheel
  stage: build:py3
  only:
    - develop
    - tags
  dependencies:
    - build:linux
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - linux

build_mac_py3:
  script:
    - FC=gfortran-6 CC=gcc-6 python3.6 setup.py bdist_wheel
  stage: build:py3
  only:
    - develop
    - tags
  dependencies:
    - build:mac
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - mac

build_windows_py3:
  script:
    - python setup.py bdist_wheel
  stage: build:py3
  only:
    - develop
    - tags
  dependencies:
    - build:windows
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - windows

# install stage installs python2 linux package on Joule

install:linux:py:
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfix || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*27*.whl --prefix=${PYPATH}
  stage: deploy
  only:
    - develop
    - tags
  dependencies:
    - build_linux_py2
  tags:
    - linux
