#image: python:2.7

cache:
  key: "$CI_BUILD_NAME"
  untracked: true
  paths:
    - build/

stages:
  - build

build_job:
  stage: build
  script:
    - ./configure_mfix --dmp
    - make mfix postmfix
  artifacts:
    paths:
    - mfix
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
