#image: python:2.7

before_script:
  - Xvfb :1 &
  - export DISPLAY=:1
  - pip install coverage

stages:
  - test

conda:
  stage: test
  script:
    - pip install -q qtpy
    - pip install -q future
    - cd tutorials/FluidBed_DES
    - ../../configure_mfix && make -j
    - MFIX_NO_VTK=yes python -m unittest discover -s gui
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
