#image: python:2.7

before_script:
  - export DISPLAY=dell57:0.0
  - pip install coverage

stages:
  - test

conda:
  stage: test
  script:
    - conda install -y -q vtk
    - pip install -q qtpy
    - pip install -q future
    - python -m unittests discover -s gui
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
