#image: python:2.7

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - build/

before_script:
  - Xvfb :1 &
  - export DISPLAY=:1

stages:
  - test

conda:
  stage: test
  script:
    - pushd tutorials/FluidBed_DES
    - ../../configure_mfix && make -j
    - popd
    - MFIX_NO_VTK=yes python -m unittest discover -s gui
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
