#image: python:2.7

cache:
  key: "$CI_BUILD_NAME"
  untracked: true
  paths:
    - build/

stages:
  - test

with_exe:
  stage: test
  script:
    - ./configure_mfix --python && make -j mfix
    - make -C gui test
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2

without_exe:
  stage: test
  script:
    - find . -type f -name mfix -exec rm -f {} \;
    - find . -type f -name pymfix -exec rm -f {} \;
    - make -C gui test
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
