stages:
  - test
  - build
  - deploy

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# test:
#   script:
#     - python setup.py test_load_all
#   stage: test
#   only:
#     - develop
#     - tags
#   tags:
#     - windows

# build:src builds a source distribution tarball

# build:src:
#   script:
#     - python setup.py sdist
#   stage: build:src
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/*.tar.gz
#   tags:
#     - linux

# build:py2 stage builds python2 wheel packages
linux_py3_conda:
  image: mwm126/mfix:latest
  script:
    - env PATH=/opt/miniconda/bin:$PATH conda build --python 3.6 build-aux/meta.yaml
    - rm -rf dist
    - mkdir -p dist
    - cp $(env PATH=/opt/miniconda/bin:$PATH conda build --output --python 3.6 build-aux/meta.yaml) dist
    # - cp /opt/miniconda/conda-bld/linux-64/*.whl dist
    - ls dist

  stage: build
  only:
    - ci_reorg
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.tar.gz
  tags:
    - docker

# build:py2 stage builds python2 wheel packages

linux_py2_whl:
  script:
    - /nfs/home/0/users/jenkins/miniconda2/bin/python2.7 setup.py bdist_wheel
  stage: build
  only:
    - ci_reorg
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - linux

# build_mac_py2:
#   script:
#     - FC=gfortran-6 CC=gcc-6 $HOME/anaconda2/bin/python2.7 setup.py bdist_wheel
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:
#     - mac

# build_mac_py3:
#   script:
#     - FC=gfortran-6 CC=gcc-6 python3.6 setup.py bdist_wheel
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:
#     - mac

# windows_py2_conda:
#   script:
#     - conda build --python 2.7 build-aux/meta.yaml
#     - rm -rf dist
#     - mkdir -p dist
#     # - cp $(conda build --output --python 2.7 build-aux/meta.yaml) dist
#     - ls -t /c/miniconda3/conda-bld/win-64 | tail -n 1 | xargs -i cp {} dist
#   stage: build
#   only:
#     - ci_reorg
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.tar.gz
#   tags:
#     - windows

windows_py3_conda:
  script:
    - conda build --python 3.4 build-aux/meta.yaml
    - rm -rf dist
    - mkdir dist
    # - cp $(conda build --output --python 3.4 build-aux/meta.yaml) dist
    - ls -t /c/miniconda3/conda-bld/win-64/mfix*.bz2 | head -n 1 | xargs -i cp {} dist
  stage: build
  only:
    - ci_reorg
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.bz2
  tags:
    - windows

# install stage installs python2 linux package on Joule

install:linux:py:
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfix || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*27*.whl --prefix=${PYPATH}
  stage: deploy
  only:
    - develop
    - tags
  dependencies:
    - linux_py2_whl
  tags:
    - linux
