# cache:
#   key: "$CI_BUILD_REF_NAME"
#   untracked: true
#   paths:
#     - build/

stages:
  - build
  - install

build_job:
  stage: build
  script:
    - env PYTHON_BIN=/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin/python ./configure_mfix --python
    - make
  artifacts:
    expire_in: 1 week
    paths:
    - mfix
    - mfixsolver*
  only:
    - branches
  tags:
    - mfixgui

install_job:
  stage: install
  script:
    - env PYTHONPATH=/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME/lib/python2.7/site-packages /nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin/python setup.py bdist_wheel -d /nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME
    - /nfs/home/0/users/jenkins/miniconda3/bin/python setup.py bdist_wheel -d /nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME
    - env PYTHONPATH=/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME/lib/python2.7/site-packages /nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin/pip uninstall mfixgui
    - env PYTHONPATH=/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME/lib/python2.7/site-packages /nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin/pip install /nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME/*cp27*.whl --prefix=/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME
  only:
    - branches
  tags:
    - mfixgui
