# cache:
#   key: "$CI_BUILD_REF_NAME"
#   untracked: true
#   paths:
#     - build/

stages:
  - build
  - install

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"
build_job:
  stage: build
  script:
    - env PYTHON_BIN=${ANACONDA_BIN}/python ./configure_mfix --python
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/python setup.py bdist_wheel -d ${PYPATH}
    - /nfs/home/0/users/jenkins/miniconda3/bin/python setup.py bdist_wheel -d ${PYPATH}
  artifacts:
    expire_in: 1 week
    paths:
    - ${PYPATH}/mfixgui*.whl
  only:
    - branches
  tags:
    - mfixgui
    - linux

install_job:
  stage: install
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfixgui
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install ${PYPATH}/*cp27*.whl --prefix=${PYPATH}
  only:
    - branches
  tags:
    - mfixgui
    - linux

build_job_mac:
  stage: build
  script:
    - env PYTHON_BIN=$HOME/anaconda2/bin/python FC=gfortran-6 CC=gcc-6 ./configure_mfix --python
    - $HOME/anaconda2/bin/python setup.py bdist_wheel
  artifacts:
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mfixgui
    - mac
