# cache:
#   key: "$CI_BUILD_REF_NAME"
#   untracked: true
#   paths:
#     - build/

stages:
  - build
  - install

build_job:
  stage: build
  script:
    - env PYTHON_BIN=/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin/python ./configure_mfix --python
    - make
  artifacts:
    expire_in: 1 week
    paths:
    - mfix
    - mfixsolver*
  only:
    - branches
  tags:
    - mfixgui

install_job:
  stage: install
  script:
    - env PYTHONPATH=/nfs/home/8/public/mfixgui/lib/python2.7/site-packages python setup.py install --prefix=/nfs/home/8/public/mfixgui
  only:
    - branches
  tags:
    - mfixgui
