stages:
  # - test
  - build
  - deploy

variables:
  AC_BIN: "/nfs/apps/autoconf/2.69/gnu/4.6.4/bin"
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  GCC_BIN: "/nfs/apps/Compilers/GNU/6.1.0/bin"
  MINICONDA3_BIN: "/nfs/home/0/users/jenkins/miniconda3/bin"
  MINICONDA3_BLD: "/nfs/home/0/users/jenkins/miniconda3/conda-bld"
  MINICONDA_BIN: "/nfs/home/0/users/jenkins/miniconda2/bin"
  MINICONDA_BLD: "/nfs/home/0/users/jenkins/miniconda2/conda-bld"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

# test:
#   script:
#     - python setup.py test_load_all
#   stage: test
#   only:
#     - develop
#     - tags
#   tags:
#     - windows

# build:src builds a source distribution tarball

# build:src:
#   script:
#     - env PATH="$AC_BIN:$GCC_BIN:$MINICONDA_BIN:$PATH" python2.7 setup.py sdist
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/*.tar.gz
#   tags:
#     - linux


linux_py3_conda:
  image: mwm126/mfix:latest
  script:
    - env PATH="$AC_BIN:$MINICONDA3_BIN:$GCC_BIN:$PATH" conda build --python 3.6 build-aux/meta.yaml
    - rm -rf dist
    - mkdir -p dist
    - ls -t "$MINICONDA_BLD/linux-64/mfix*.bz2" | head -n 1 | xargs -i cp {} dist
    - ls dist
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/mfix*.bz2
  tags:
    - linux

linux_py2_whl:
  variables:
  script:
    - env PATH="$AC_BIN:$MINICONDA_BIN:$GCC_BIN:$PATH" python2.7 setup.py bdist_wheel
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - linux

# build_mac_py2:
#   script:
#     - FC=gfortran-6 CC=gcc-6 $HOME/anaconda2/bin/python2.7 setup.py bdist_wheel
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:
#     - mac

# build_mac_py3:
#   script:
#     - FC=gfortran-6 CC=gcc-6 python3.6 setup.py bdist_wheel
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.whl
#   tags:

# windows_py2_conda:
#   script:
#     - conda build --python 2.7 build-aux/meta.yaml
#     - rm -rf dist
#     - mkdir -p dist
#     # - cp $(conda build --output --python 2.7 build-aux/meta.yaml) dist
#     - ls -t /c/miniconda3/conda-bld/win-64 | tail -n 1 | xargs -i cp {} dist
#   stage: build
#   only:
#     - develop
#     - tags
#   artifacts:
#     name: "$CI_BUILD_NAME"
#     expire_in: 1 week
#     paths:
#     - dist/mfix*.tar.gz
#   tags:
#     - windows

windows_py3_conda:
  script:
    - conda build --python 3.4 build-aux/meta.yaml
    - rm -rf dist
    - mkdir dist
    # - cp $(conda build --output --python 3.4 build-aux/meta.yaml) dist
    - ls -t /c/Users/mmeredith/miniconda3/conda-bld/win-64/mfix*.bz2 | head -n 1 | xargs -i cp {} dist
    - ls dist
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
      - dist/mfix*.bz2
  tags:
    - windows

windows_py3_whl:
  script:
    - python setup.py bdist_wheel
  stage: build
  only:
    - develop
    - tags
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfix*.whl
  tags:
    - windows

install:linux:py:
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfix || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*27*.whl --prefix=${PYPATH}
  stage: deploy
  only:
    - develop
    - tags
  dependencies:
    - linux_py2_whl
  tags:
    - linux
