stages:
  - build:py2
  - build:py3
  - deploy

variables:
  ANACONDA_BIN: "/nfs/apps/Compilers/Python/Anaconda/2.7/x86-64/bin"
  PYPATH: "/nfs/home/8/public/mfixgui/branches/$CI_BUILD_REF_NAME"

build:linux:py2:
  stage: build:py2
  script:
    - git clean -fdx
    - env PYTHON_VERSION=2.7 /nfs/home/0/users/jenkins/miniconda2/bin/python setup.py bdist_wheel
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - linux

build:linux:py3:
  stage: build:py3
  script:
    - git clean -fdx
    - env PYTHON_VERSION=3.5 /nfs/home/0/users/jenkins/miniconda3/bin/python setup.py bdist_wheel
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - linux

install:linux:py2:
  stage: deploy
  script:
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip uninstall --yes mfixgui || true
    - env PYTHONPATH=${PYPATH}/lib/python2.7/site-packages ${ANACONDA_BIN}/pip install dist/*.whl --prefix=${PYPATH}
  dependencies:
    - build:linux:py2
  only:
    - branches
  tags:
    - linux

build:mac:py2:
  stage: build:py2
  script:
    - git clean -fdx
    - env FC=gfortran-6 CC=gcc-6 $HOME/anaconda2/bin/python setup.py bdist_wheel
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mac

build:mac:py3:
  stage: build:py3
  script:
    - git clean -fdx
    - env FC=gfortran-6 CC=gcc-6 $HOME/miniconda3/bin/python3 setup.py bdist_wheel
  artifacts:
    name: "$CI_BUILD_NAME"
    expire_in: 1 week
    paths:
    - dist/mfixgui*.whl
  only:
    - branches
  tags:
    - mac
