#image: python:2.7

before_script:
  - export DISPLAY=dell57:0.0
  - pip install coverage

stages:
  - test

conda:
  stage: test
  script:
    - apt-get install libgl1-mesa-glx libglu1-mesa libxt6
    - conda install -y -q vtk
    - pip install -q qtpy
    - pip install -q future
    - python -m unittest discover -s gui
  only:
    - branches
  tags:
    - docker
    - anaconda
    - python2
