#!/bin/bash -e
#
#  Wrapper script for calling configure in MFIX_HOME and copying Makefile.usr into $PWD
#

# Set some of the folder paths.
RUN_DIR=$(pwd)
MFIX_HOME=$(cd $(dirname $0); pwd)
BUILD_DIR=${MFIX_HOME}/build

cd ${MFIX_HOME}
[ -f configure ] || autoreconf -i

cd ${BUILD_DIR}
${MFIX_HOME}/configure "$@" || exit

MAKEFILE=${RUN_DIR}/Makefile
MAKEFILE_USR=${BUILD_DIR}/build-aux/Makefile.usr
if [ -f ${MAKEFILE_USR} ] && [ ${PWD} != ${RUN_DIR} ]; then
    cp ${MAKEFILE_USR} ${MAKEFILE}
fi
