#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$script_dir/../../configure --enable-dmp FC=mpif90 F77=mpif90 FCFLAGS="-ffree-line-length-none -fopenmp" LDFLAGS="-fopenmp"
