
!                           Gas phase speciesindices     
      INTEGER, PARAMETER :: O2   = 1, &
      	       		    N2   = 2, &
                            H2O  = 3, &
			    CO   = 4, &
                            CO2  = 5, &
			    H2   = 6, &
			    CH4  = 7, &
			    TAR  = 8, &
			    TARIN= 9
			    
!                           Solids phase speciesindex     
      INTEGER, PARAMETER :: BIO        = 1, &
      	                    LMOISTURE      = 2, &
                            BIOCHAR        = 3, &
                            VOID           = 4, &
			    ASH            = 5
