#!/bin/tcsh 
rm -f */*.RES */*.SP* */*.LOG
echo
cd cond_conv
echo "********************************************************************"
echo "cond_conv" 
tail -20 out1 
cd ..
# Another case
echo
cd conduction
echo "********************************************************************"
echo "conduction"
tail -20 out1 
cd ..
# Another case
echo
cd conduction2
echo "********************************************************************"
echo "conduction2"
tail -20 out1 
cd ..
# Another case
echo
cd cyclic-shear
echo "********************************************************************"
echo "cyclic-shear"
tail -20 out1 
cd ..
# Another case
echo
cd developed_pipe_flow
echo "********************************************************************"
echo "developed_pipe_flow"
tail -20 out1 
cd ..
# Another case
echo
cd developed_pipe_flow1
echo "********************************************************************"
echo "developed_pipe_flow1"
tail -20 out1 
cd ..
# Another case
echo
cd developed_slit_flow
echo "********************************************************************"
echo "developed_slit_flow"
tail -20 out1 
cd ..
# Another case
echo
cd dmp_test
echo "********************************************************************"
echo "dmp_test"
tail -20 out1 
cd ..
# Another case
echo
cd dmp_test_cyclic
echo "********************************************************************"
echo "dmp_test_cyclic"
tail -20 out1 
cd ..
# Another case
echo
cd driven-cavity
echo "********************************************************************"
echo "driven-cavity"
tail -20 out1 
cd ..
# Another case
echo
cd fluidBed1SI
echo "********************************************************************"
echo "fluidBed1SI"
tail -20 out1 
cd ..
# Another case
echo
cd granular_shear
echo "********************************************************************"
echo "granular_shear"
tail -20 out1 
cd ..
# Another case
echo
cd ozone
echo "********************************************************************"
echo "ozone"
tail -20 out1 
cd ..
# Another case
echo
cd packed-bed
echo "********************************************************************"
echo "packed-bed"
tail -20 out1 
cd ..
# Another case
echo
cd phase-change
echo "********************************************************************"
echo "phase-change"
tail -20 out1 
cd ..
# Another case
echo
cd rotary-drum
echo "********************************************************************"
echo "rotary-drum"
tail -20 out1 
cd ..
# Another case
echo
cd segregation
echo "********************************************************************"
echo "segregation"
tail -20 out1 
cd ..
# Another case
echo
cd settling-tank
echo "********************************************************************"
echo "settling-tank"
tail -20 out1 
cd ..
# Another case
echo
cd simple-2phase
echo "********************************************************************"
echo "simple-2phase"
tail -20 out1 
cd ..
# Another case
echo
cd solid-body-rotation
echo "********************************************************************"
echo "solid-body-rotation"
tail -20 out1 
cd ..
# Another case
echo
cd tsuji
echo "********************************************************************"
echo "tsuji"
tail -20 out1 
cd ..
# Another case
echo "Testing is over.  Check the output for timing and any errors"
