#!/bin/tcsh 
rm -f */*.RES */*.SP* */*.LOG */*.OUT */*.out */*.*~
# Another case
echo
cd chi-scheme
echo "********************************************************************"
echo "chi-scheme"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd cond_conv
echo "********************************************************************"
echo "cond_conv"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd conduction
echo "********************************************************************"
echo "conduction"
conduction
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd conduction2
echo "********************************************************************"
echo "conduction2"
conduction2
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd cyclic-shear
echo "********************************************************************"
echo "cyclic-shear"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd Driven_Cavity_DES
echo "********************************************************************"
echo "Driven_Cavity_DES"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd developed_pipe_flow
echo "********************************************************************"
echo "developed_pipe_flow"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd developed_pipe_flow1
echo "********************************************************************"
echo "developed_pipe_flow1"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd developed_slit_flow
echo "********************************************************************"
echo "developed_slit_flow"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd dmp_test
echo "********************************************************************"
echo "dmp_test"
dmp_test
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd dmp_test_cyclic
echo "********************************************************************"
echo "dmp_test_cyclic"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd driven-cavity
echo "********************************************************************"
echo "driven-cavity"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd fluidBed1SI
echo "********************************************************************"
echo "fluidBed1SI"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd fluidBed1_cn
echo "********************************************************************"
echo "fluidBed1_cn"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd fluidBed1_4th
echo "********************************************************************"
echo "fluidBed1_4th"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd hopper
echo "********************************************************************"
echo "hopper"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd granular_shear
echo "********************************************************************"
echo "granular_shear"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd Kink_DES
echo "********************************************************************"
echo "Kink_DES"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd ozone
echo "********************************************************************"
echo "ozone"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd packed-bed
echo "********************************************************************"
echo "packed-bed"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd phase-change
echo "********************************************************************"
echo "phase-change"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd periodic-flow-fixed-mass-flux
echo "********************************************************************"
echo "periodic-flow-fixed-mass-flux"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd rotary-drum
echo "********************************************************************"
echo "rotary-drum"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd segregation
echo "********************************************************************"
echo "segregation"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd settling-tank
echo "********************************************************************"
echo "settling-tank"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd simple-2phase
echo "********************************************************************"
echo "simple-2phase"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd solid-body-rotation
echo "********************************************************************"
echo "solid-body-rotation"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd tsuji
echo "********************************************************************"
echo "tsuji"
tsuji
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd 2Dfluidbed_VDW_high_coh
echo "********************************************************************"
echo "2Dfluidbed_VDW_high_coh"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd driven_cavity_cohesion_VDW
echo "********************************************************************"
echo "driven_cavity_cohesion_VDW"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd isat
echo "********************************************************************"
echo "isat"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd dqmom
echo "********************************************************************"
echo "dqmom"
sh ~/MFIX/mfix/model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo "Testing is over.  Check the output for timing and any errors"
