#!/bin/csh -ex
## Change into the current working directory
#$ -cwd
##
## The name for the job. It will be displayed this way on qstat
#$ -N ${JOB_NAME}
##
## Number of cores to request
#$ -pe dev ${CORES}
##
#$ -r n
##
## Queue Name
#$ -q ${QUEUE}


##Load Modules
#module ${MODULES}

##Run the parallel job
mpirun -np ${CORES} ${COMMAND}
