#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$script_dir/../../configure --host=x86_64-k1om-linux FC=ifort F77=ifort FFLAGS="-mmic" FCFLAGS="-openmp -mmic" LDFLAGS="-openmp -mmic"
