      MODULE stl
 

      Use param 
      Use param1

!     Maximum of the number of polygons that can be read 
      INTEGER, PARAMETER          :: DIM_STL = 10000000   !10 Million
!     Number of facets
      INTEGER                     :: N_FACETS
!     Vertex Coordinates X ,Y and Z
      DOUBLE PRECISION, DIMENSION(DIM_STL,3,3) :: VERTEX
!     Face normal vector (normalized)
      DOUBLE PRECISION, DIMENSION(DIM_STL,3) :: NORM_FACE
!     TRANSLATION COMPONENTS
      DOUBLE PRECISION :: TX_STL,TY_STL,TZ_STL  
      DOUBLE PRECISION :: TX_MSH,TY_MSH,TZ_MSH  
!     SCALING FACTOR
      DOUBLE PRECISION :: SCALE_STL
      DOUBLE PRECISION :: SCALE_MSH
!     RANGE OF STL FILE:
      DOUBLE PRECISION :: XMIN_STL,XMAX_STL
      DOUBLE PRECISION :: YMIN_STL,YMAX_STL
      DOUBLE PRECISION :: ZMIN_STL,ZMAX_STL
      DOUBLE PRECISION :: XMIN_MSH,XMAX_MSH
      DOUBLE PRECISION :: YMIN_MSH,YMAX_MSH
      DOUBLE PRECISION :: ZMIN_MSH,ZMAX_MSH
!     VALUE OF F_STL OUTSIDE OF STL BOUNDING BOX
      DOUBLE PRECISION :: OUT_STL_VALUE
      DOUBLE PRECISION :: OUT_MSH_VALUE
!     SMALLEST ANGLE FOR DETECTION OF SMALL TRIANGLES
      DOUBLE PRECISION :: STL_SMALL_ANGLE
      DOUBLE PRECISION :: MSH_SMALL_ANGLE
!     DIRECTION OF RAY TRACED TO DETERMINE WHETHER A POINT IS INSIDE/OUTSIDE
      CHARACTER(LEN=3) :: RAY_DIR
!     Tolerance for polygone edge detection
      DOUBLE PRECISION :: TOL_STL
      DOUBLE PRECISION :: TOL_MSH
!     Boundary condition ID
      INTEGER :: STL_BC_ID

      INTEGER, DIMENSION(DIM_STL) :: BC_ID_STL_FACE

      INTEGER, DIMENSION (:), ALLOCATABLE ::  N_FACET_AT 
      INTEGER, DIMENSION (:,:), ALLOCATABLE ::  LIST_FACET_AT 

      CHARACTER(LEN=3) :: CAD_PROPAGATE_ORDER

      END MODULE stl
