#!/bin/tcsh 
# Script to run all the tutorial cases in serial
rm -f */*.RES */*.SP* */*.LOG */*.OUT */*/*.RES */*/*.SP* */*/*.LOG */*/*.OUT */*.vtp
echo
cd 3dCfb
echo "********************************************************************"
echo "3dCfb"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd 3dFluidbed
echo "********************************************************************"
echo "3dFluidbed"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd FluidBed_DES
echo "********************************************************************"
echo "FluidBed_DES"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ../
# Another case
echo
cd fluidBed1
echo "********************************************************************"
echo "fluidBed1"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd fluidBed2
echo "********************************************************************"
echo "fluidBed2"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd reactor1a
echo "********************************************************************"
echo "reactor1a"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd reactor1b
echo "********************************************************************"
echo "reactor1b"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ..
# Another case
echo
cd SpoutedBedCombustor
echo "********************************************************************"
echo "SpoutedBedCombustor"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ../
# Another case
echo
cd Fully_Developed_With_AhmadiModel
echo "********************************************************************"
echo "Fully_Developed_With_AhmadiModel"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ../
# Another case
echo
cd Gidaspow_fbed_With_SimoninModel
echo "********************************************************************"
echo "Gidaspow_fbed_With_SimoninModel"
sh ../../model/make_mfix < ../in
./mfix.exe > out1
cd ../
