!vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvC
!                                                                         C
!     Module name: DISCRETELEMENT                                         C
!     Purpose: DES mod file                                               C
!                                                                         C
!                                                                         C
!     Author: Jay Boyalakuntla                           Date: 12-Jun-04  C
!     Reviewer:                                          Date:            C
!                                                                         C
!^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^C
!     
!     Common Block containing DEM conditions 
!     

      MODULE DISCRETELEMENT


      Use param
      Use param1
      
      parameter (NPARTICLES = 5000)
      parameter (MAXNEIGHBORS = 12)
      parameter (MAXQUADS = 50000)
      parameter (NMQD = 11)
      parameter (NDIM = 3)
      parameter (NWALLS = 6)

      INTEGER NEIGHBOURS(MAXNEIGHBORS,NPARTICLES)
      INTEGER PN(MAXNEIGHBORS,NPARTICLES), PV(MAXNEIGHBORS,NPARTICLES)
      INTEGER CALLED, PCOUNT, FACTOR
      INTEGER PARTICLES, MN, NQUAD, DIMN, ZONES, ZN1, ZN2, ZN3, ZN4
      INTEGER NEIGHBOR, WALLCONTACT, OUTOFBOX
      INTEGER LQUAD(NMQD,MAXQUADS), PINC(NPARTICLES)
      
      DOUBLE PRECISION DES_POS_OLD(NDIM,NPARTICLES)
      DOUBLE PRECISION DES_POS_NEW(NDIM,NPARTICLES)
      DOUBLE PRECISION DES_RADIUS(NPARTICLES), PR(NPARTICLES)
      DOUBLE PRECISION DES_VEL_OLD(NDIM,NPARTICLES)
      DOUBLE PRECISION DES_VEL_NEW(NDIM,NPARTICLES)
      DOUBLE PRECISION FC(NDIM,NPARTICLES)
      DOUBLE PRECISION FN(NDIM,NPARTICLES)
      DOUBLE PRECISION FT(NDIM,NPARTICLES) 
      DOUBLE PRECISION TOW(NDIM,NPARTICLES)
      DOUBLE PRECISION KN, KN_W
      DOUBLE PRECISION KT, KT_W 
      DOUBLE PRECISION ETA_DES_N, ETA_N_W
      DOUBLE PRECISION ETA_DES_T, ETA_T_W
      DOUBLE PRECISION MEW, MEW_W, E_RESTITUTION, DES_GAMMA, DES_F
      DOUBLE PRECISION DES_KE, DES_PE
      DOUBLE PRECISION OMEGA_OLD(NDIM,NPARTICLES)
      DOUBLE PRECISION OMEGA_NEW(NDIM,NPARTICLES)
      DOUBLE PRECISION WX1, EX2, BY1, TY2, SZ1, NZ2
      DOUBLE PRECISION DES_WALL_POS(NDIM,NWALLS), DES_WALL_VEL(NDIM,NWALLS)
      DOUBLE PRECISION RADIUS_EQ, WALL_NORMAL(NDIM,NWALLS)
      DOUBLE PRECISION PFN(NDIM,MAXNEIGHBORS,NPARTICLES)
      DOUBLE PRECISION PFT(NDIM,MAXNEIGHBORS,NPARTICLES)
      DOUBLE PRECISION CQUAD(NWALLS,MAXQUADS)
      DOUBLE PRECISION DTSOLID, RO_Sol(NPARTICLES)
      DOUBLE PRECISION N2CT, NBSCT, QUADCT, OCTCT
      DOUBLE PRECISION FNS1(NDIM), FTS1(NDIM)
      DOUBLE PRECISION PMASS(NPARTICLES), MOI(NPARTICLES), GRAV(NDIM), ROs
      DOUBLE PRECISION DES_THETA(NPARTICLES,NDIM)

      LOGICAL DISCRETE_ELEMENT 
      LOGICAL DES_CONTINUUM_COUPLED
      LOGICAL COUPLED_FLOW
      LOGICAL DO_NBS
      LOGICAL DO_QUADTREE
      LOGICAL DO_OCTREE
      LOGICAL DO_NSQUARE
      LOGICAL WALLFIXEDOVERLAP
      LOGICAL WALLDTSPLIT
      LOGICAL WALLREFLECT
      LOGICAL DES_PERIODIC_WALLS
      LOGICAL DES_PERIODIC_WALLS_X
      LOGICAL DES_PERIODIC_WALLS_Y
      LOGICAL DES_PERIODIC_WALLS_Z
      LOGICAL INLET_OUTLET
      LOGICAL TIME_ADJUST
      LOGICAL EQUIVALENT_RADIUS
      LOGICAL TSUJI_DRAG
      LOGICAL KUIPERS_DRAG

      END MODULE DISCRETELEMENT
