C
C                      Dummy arguments
      DOUBLE PRECISION XXXp, XXXm
C
C                      Dummy indices
      INTEGER          xL
C
C                      average at i+1/2 location
      DOUBLE PRECISION AVG_X
C
C                      average (of U) at i+1 location
      DOUBLE PRECISION AVG_X_E
C
C                      average at j+1/2 location
      DOUBLE PRECISION AVG_Y
C
C                      average (of V) at j+1 location
      DOUBLE PRECISION AVG_Y_N
C
C                      average at k+1/2 location
      DOUBLE PRECISION AVG_Z
C
C                      average (of W) at k+1 location
      DOUBLE PRECISION AVG_Z_T
C
C                      Harmonic average at i+1/2 location
      DOUBLE PRECISION AVG_X_h
C
C                      Harmonic averageat j+1/2 location
      DOUBLE PRECISION AVG_Y_h
C
C                      Harmonic average at k+1/2 location
      DOUBLE PRECISION AVG_Z_h
