      SUBROUTINE GET_FILE_STATUS(STATUS_CODE,FILE_NAME)
C
      IMPLICIT NONE
C
      INTEGER         STATUS_CODE
      CHARACTER*(*)   FILE_NAME
      LOGICAL         FILE_EXISTS
C
      INQUIRE (FILE=FILE_NAME,EXIST=FILE_EXISTS)
C
      IF (FILE_EXISTS) THEN
         STATUS_CODE = 1
      ELSE
         STATUS_CODE = 0
      END IF
C
      RETURN
      END
