CvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvC
C                                                                      C
C  Module name: scales.inc                                             C
C
C                      reference pressure
      DOUBLE PRECISION P_ref
C
C                      pressure scale
      DOUBLE PRECISION P_scale
C
C
      COMMON / SCALES_DP /
     &       P_ref, P_scale
C
C      COMMON / SCALES_I /
C     & 
C
C      COMMON / SCALES_L /
C     &       
C
C      COMMON / SCALES_C /
C     &      
C
