#!/bin/bash -lex

module load gnu/4.6.4

../../../configure_mfix  FC=gfortran FCFLAGS="-O0 -g"
make

RUN_NAME="DEM04"

DES_IM=ADAMS_BASHFORTH
for DES_MEW in 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0; do
  rm -f ${RUN_NAME}* &> /dev/null
  time -p ./mfix DES_INTG_METHOD=\"${DES_IM}\" \
    MEW=${DES_MEW} MEW_W=${DES_MEW}
done


#diff -q POST_posvel.dat AUTOTEST/POST_posvel.dat
