#!/bin/bash -lx

module load autoconf/2.69
module load gnu/4.6.4

MFIX=${MFIX_HOME-"../../../"}

GCC_DBGFLAGS="-fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow"
${MFIX}/configure_mfix FC=gfortran FCFLAGS="-O0 $GCC_DBGFLAGS" || exit $?
make clean
make || exit $?

rm POST_*.dat &> /dev/null

RUN_NAME="DEM06"

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.T. \
    DES_INTERP_ON=.F. DES_INTERP_MEAN_FIELDS=.F.

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.T. \
    DES_INTERP_ON=.T. DES_INTERP_MEAN_FIELDS=.T. \
    DES_INTERP_SCHEME=\'GARG_2012\'

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.T. \
    DES_INTERP_ON=.T. DES_INTERP_MEAN_FIELDS=.T. \
    DES_INTERP_SCHEME=\'SQUARE_DPVM\' DES_INTERP_WIDTH=2.0d-3

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.F. \
    DES_INTERP_ON=.F. DES_INTERP_MEAN_FIELDS=.F.

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.F. \
    DES_INTERP_ON=.T. DES_INTERP_MEAN_FIELDS=.T. \
    DES_INTERP_SCHEME=\'GARG_2012\'

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.F. \
    DES_INTERP_ON=.T. DES_INTERP_MEAN_FIELDS=.T. \
    DES_INTERP_SCHEME=\'SQUARE_DPVM\' DES_INTERP_WIDTH=3.0d-3

rm -f ${RUN_NAME}* &> /dev/null
time -p ./mfix DES_ONEWAY_COUPLED=.F. \
    DES_INTERP_ON=.T. DES_INTERP_MEAN_FIELDS=.T. \
    DES_INTERP_SCHEME=\'SQUARE_DPVM\' DES_INTERP_WIDTH=4.0d-3
