#!/bin/csh -f
#main
echo "Creating post_l.make ..."

cd ../post_mfix

if( -e machine.f ) then 
  echo 
  echo "machine.f already exists, so not copying a temporary file from model"
  echo
  else	    
  echo
  echo "machine.f already does not exist, so copying a temporary file from model "
  echo "in order to create the make files"
  echo
  /bin/cp -f ../model/LINUX.F machine.f
  touch remove_machine 
endif 


../tools/mms_post.exe
if ($status == 0) then
  echo
  echo "post_u.make created"
  echo "post_l.make created"
  echo
else
  echo
  echo "*** make files not created ***"
  echo "Perhaps mms_post.exe needs to be created (f90 -o mms_post.exe mms_post.f)"
  echo
endif

if (-e remove_machine) then 
    echo
    echo "machine.f that was copied from model directory is deleted"
    echo 
    rm -f machine.f remove_machine
endif 
