#!/bin/csh -f
#main
echo "Creating mfix.make ..."
cd ../model
ls -1 *.f>files.lis
set dir = $cwd
foreach i (*)
  if(-d $i)then
    cd $i
    #test -e *.f
    ls *.f >tmp.tmp
    if ($status == 0) then
      foreach file (*.f)
        echo "./$i/$file">>$dir/files.lis
      end
    endif
    cd ..
  endif
end
../tools/mms.exe
if ($status == 0) then
  echo
  echo "mfix_u.make created"
  echo "mfix_l.make created"

  sed -e "s|-module |-J|g" <mfix_l.make> tmp1
  mv tmp1 mfix_l.make_gfor

  sed -e "s|-module |-J|g" <mfix_u.make> tmp1
  mv tmp1 mfix_u.make_gfor

  echo
else
  echo
  echo "*** make files not created ***"
  echo "Perhaps mms.exe needs to be created (f90 -o mms.exe mms.f)"
  echo
endif
